document.addEventListener('DOMContentLoaded',()=>{
 const $=id=>document.getElementById(id); const q=new URLSearchParams(location.search); const isHost=q.has('host')||q.has('create'); const isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(/Macintosh/.test(navigator.userAgent)&&navigator.maxTouchPoints>1);
 const share=$('share'); if(share) share.hidden=isHost;
 if(!isHost) return;
 const video=$('video'),empty=$('empty'); let token='',reader=null,started=false,poll=0,lastEvent=0,canvas=null,ctx=null,decoder=null;
 const bases=['http://127.0.0.1:8765','http://localhost:8765'];
 async function api(path,opts={}){for(const b of bases){try{const r=await fetch(b+path,{...opts,cache:'no-store'});if(r.ok)return await r.json()}catch(_){}}throw 0}
 function ensureCanvas(){if(canvas)return;canvas=document.createElement('canvas');canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;object-fit:contain;background:#02050a';canvas.hidden=true;video.parentElement.appendChild(canvas);ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});}
 async function startVideo(){if(started)return;started=true;ensureCanvas();try{if(typeof VideoDecoder==='undefined') throw new Error('WebCodecs unavailable');const r=await fetch('http://127.0.0.1:8765/airplay/video',{cache:'no-store',headers:{'X-CastScreen-Agent-Token':token}});if(!r.ok||!r.body)throw 0;reader=r.body.getReader();decoder=new VideoDecoder({output:frame=>{canvas.width=frame.displayWidth;canvas.height=frame.displayHeight;const sharp=Math.min(1,Number(localStorage.getItem('castscreen_sharpen')||0)/100);ctx.filter=sharp?'contrast('+Math.min(1.18,1+sharp*.12)+') saturate('+Math.min(1.12,1+sharp*.08)+')':'none';ctx.drawImage(frame,0,0,canvas.width,canvas.height);frame.close();canvas.hidden=false;video.hidden=true;empty.style.display='none'},error:e=>console.warn('[CastScreen] AirPlay decode',e)});decoder.configure({codec:'avc1.640028',optimizeForLatency:true});let buf=new Uint8Array(0);while(reader){const {value,done}=await reader.read();if(done)break;if(!value)continue;const n=new Uint8Array(buf.length+value.length);n.set(buf);n.set(value,buf.length);buf=n;while(buf.length>=13){const dv=new DataView(buf.buffer,buf.byteOffset,buf.byteLength);const len=dv.getUint32(0);if(len<9||buf.length<4+len)break;const pts=Number(dv.getBigUint64(4)),key=!!buf[12],payload=buf.slice(13,4+len);decoder.decode(new EncodedVideoChunk({type:key?'key':'delta',timestamp:pts,data:payload}));buf=buf.slice(4+len)}}}catch(e){console.warn('[CastScreen] Host AirPlay web video unavailable',e)}finally{started=false;reader=null;try{decoder&&decoder.close()}catch(_){}decoder=null}}
 async function pollAgent(){try{const s=await api('/airplay/status');token=s.token||token;if(s.last_event!==lastEvent){lastEvent=s.last_event;if(s.airplay_connected&&s.approved)startVideo();} if(!s.airplay_connected){started=false}}catch(_){}poll=setTimeout(pollAgent,900)}
 pollAgent();
});
