/**
 * Cast Screen Pro Cloudflare Worker.
 * Cloud only serves UI/signaling; AirPlay media stays on the PC LAN host.
 */
const wsRooms=new Map();const httpRooms=new Map();
const ROOM_TARGET='/room_airplay.html';
async function serveAsset(request,env,target,inject=false){if(!env?.ASSETS?.fetch)return null;const a=new URL(request.url);a.pathname=target;const r=await env.ASSETS.fetch(new Request(a.toString(),request));if(!inject||r.status===404)return r;if(!(r.headers.get('content-type')||'').includes('text/html'))return r;const text=await r.text();const body=text.replace('</body>','<script src="/js/airplay_enhancer.js?v=1"></script></body>');const headers=new Headers(r.headers);headers.delete('content-length');headers.set('Cache-Control','no-cache, no-store, must-revalidate');return new Response(body,{status:r.status,statusText:r.statusText,headers});}
export default{async fetch(request,env){const url=new URL(request.url);const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization, X-Requested-With','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Cache-Control':'no-cache, no-store, must-revalidate'};if(request.method==='OPTIONS')return new Response(null,{status:200,headers:cors});
const upgrade=(request.headers.get('Upgrade')||'').toLowerCase()==='websocket';if(url.pathname==='/ws'&&upgrade){const roomId=url.searchParams.get('room')||'default';const role=url.searchParams.get('role')||'client';const pair=new WebSocketPair();const[client,server]=Object.values(pair);server.accept();if(!wsRooms.has(roomId))wsRooms.set(roomId,new Set());const peers=wsRooms.get(roomId);peers.add(server);try{server.send(JSON.stringify({type:'connected',roomId,role}))}catch(_){}server.addEventListener('message',e=>{let d=null;try{d=JSON.parse(e.data)}catch(_){}if(d?.type==='ping'){try{server.send(JSON.stringify({type:'pong',ts:Date.now()}))}catch(_){}return}for(const p of peers)if(p!==server&&p.readyState===1)try{p.send(e.data)}catch(_){}});const clean=()=>{peers.delete(server);if(!peers.size)wsRooms.delete(roomId)};server.addEventListener('close',clean);server.addEventListener('error',clean);return new Response(null,{status:101,webSocket:client,headers:cors})}
if(url.pathname==='/signal/poll'){const roomId=url.searchParams.get('room')||'default';const role=url.searchParams.get('role')||'client';const since=parseFloat(url.searchParams.get('since')||'0');const list=httpRooms.get(roomId)||[];return new Response(JSON.stringify(list.filter(m=>m.ts>since&&m.from!==role)),{status:200,headers:{...cors,'Content-Type':'application/json; charset=utf-8'}})}
if(url.pathname==='/signal/send'&&request.method==='POST'){try{const data=await request.json();const roomId=data.roomId||'default';const role=data.from||'client';if(!httpRooms.has(roomId))httpRooms.set(roomId,[]);const list=httpRooms.get(roomId);list.push({data,from:role,ts:Date.now()/1000});if(list.length>50)httpRooms.set(roomId,list.slice(-50));return new Response(JSON.stringify({status:'ok'}),{status:200,headers:{...cors,'Content-Type':'application/json'}})}catch(e){return new Response(e.message,{status:400,headers:cors})}}
if(url.pathname==='/favicon.ico')return new Response(null,{status:204,headers:cors});let target=url.pathname;if(!target||target==='/')target='/home.html';else if(target==='/join'||target==='/join.html')target='/join.html';else if(target==='/room'||target==='/room.html'||target==='/room_airplay.html'||target==='/room_v5.html')target=ROOM_TARGET;else if(target==='/download-agent')target='/download-agent.html';else if(target==='/sender')target='/sender.html';if(env?.ASSETS?.fetch){try{const r=await serveAsset(request,env,target,target===ROOM_TARGET);if(r?.status!==404)return r;if(target!==url.pathname)return await env.ASSETS.fetch(request);return r}catch(e){console.error('[Worker] Asset fetch error:',e)}}return new Response('Cast Screen WebRTC Server is active.',{status:200,headers:{...cors,'Content-Type':'text/plain; charset=utf-8'}})}};
